//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBank.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CodeBankEntities : DbContext
    {
        public CodeBankEntities()
            : base("name=CodeBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entry> Entry { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    
        public virtual int Delete_Entry(Nullable<int> entr_Code)
        {
            var entr_CodeParameter = entr_Code.HasValue ?
                new ObjectParameter("entr_Code", entr_Code) :
                new ObjectParameter("entr_Code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Entry", entr_CodeParameter);
        }
    
        public virtual int Insert_Entry(string entr_Titre, string entr_Description, string entr_Username, string entr_Password, string entr_Site, string entr_Observation, Nullable<System.DateTime> entr_Date)
        {
            var entr_TitreParameter = entr_Titre != null ?
                new ObjectParameter("entr_Titre", entr_Titre) :
                new ObjectParameter("entr_Titre", typeof(string));
    
            var entr_DescriptionParameter = entr_Description != null ?
                new ObjectParameter("entr_Description", entr_Description) :
                new ObjectParameter("entr_Description", typeof(string));
    
            var entr_UsernameParameter = entr_Username != null ?
                new ObjectParameter("entr_Username", entr_Username) :
                new ObjectParameter("entr_Username", typeof(string));
    
            var entr_PasswordParameter = entr_Password != null ?
                new ObjectParameter("entr_Password", entr_Password) :
                new ObjectParameter("entr_Password", typeof(string));
    
            var entr_SiteParameter = entr_Site != null ?
                new ObjectParameter("entr_Site", entr_Site) :
                new ObjectParameter("entr_Site", typeof(string));
    
            var entr_ObservationParameter = entr_Observation != null ?
                new ObjectParameter("entr_Observation", entr_Observation) :
                new ObjectParameter("entr_Observation", typeof(string));
    
            var entr_DateParameter = entr_Date.HasValue ?
                new ObjectParameter("entr_Date", entr_Date) :
                new ObjectParameter("entr_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Entry", entr_TitreParameter, entr_DescriptionParameter, entr_UsernameParameter, entr_PasswordParameter, entr_SiteParameter, entr_ObservationParameter, entr_DateParameter);
        }
    
        public virtual ObjectResult<Select_Entry_Result> Select_Entry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Entry_Result>("Select_Entry");
        }
    
        public virtual int Update_Entry(Nullable<int> entr_Code, string entr_Titre, string entr_Description, string entr_Username, string entr_Password, string entr_Site, string entr_Observation)
        {
            var entr_CodeParameter = entr_Code.HasValue ?
                new ObjectParameter("entr_Code", entr_Code) :
                new ObjectParameter("entr_Code", typeof(int));
    
            var entr_TitreParameter = entr_Titre != null ?
                new ObjectParameter("entr_Titre", entr_Titre) :
                new ObjectParameter("entr_Titre", typeof(string));
    
            var entr_DescriptionParameter = entr_Description != null ?
                new ObjectParameter("entr_Description", entr_Description) :
                new ObjectParameter("entr_Description", typeof(string));
    
            var entr_UsernameParameter = entr_Username != null ?
                new ObjectParameter("entr_Username", entr_Username) :
                new ObjectParameter("entr_Username", typeof(string));
    
            var entr_PasswordParameter = entr_Password != null ?
                new ObjectParameter("entr_Password", entr_Password) :
                new ObjectParameter("entr_Password", typeof(string));
    
            var entr_SiteParameter = entr_Site != null ?
                new ObjectParameter("entr_Site", entr_Site) :
                new ObjectParameter("entr_Site", typeof(string));
    
            var entr_ObservationParameter = entr_Observation != null ?
                new ObjectParameter("entr_Observation", entr_Observation) :
                new ObjectParameter("entr_Observation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Entry", entr_CodeParameter, entr_TitreParameter, entr_DescriptionParameter, entr_UsernameParameter, entr_PasswordParameter, entr_SiteParameter, entr_ObservationParameter);
        }
    
        public virtual ObjectResult<Entry> Select_Entry_By_Code(Nullable<int> entr_Code)
        {
            var entr_CodeParameter = entr_Code.HasValue ?
                new ObjectParameter("entr_Code", entr_Code) :
                new ObjectParameter("entr_Code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Entry>("Select_Entry_By_Code", entr_CodeParameter);
        }
    
        public virtual ObjectResult<Entry> Select_Entry_By_Code(Nullable<int> entr_Code, MergeOption mergeOption)
        {
            var entr_CodeParameter = entr_Code.HasValue ?
                new ObjectParameter("entr_Code", entr_Code) :
                new ObjectParameter("entr_Code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Entry>("Select_Entry_By_Code", mergeOption, entr_CodeParameter);
        }
    }
}
