//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBank.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int entr_Code { get; set; }
        public string entr_Titre { get; set; }
        public string entr_Description { get; set; }
        public string entr_Username { get; set; }
        public string entr_Password { get; set; }
        public string entr_Site { get; set; }
        public string entr_Observation { get; set; }
        public Nullable<System.DateTime> entr_Date { get; set; }
    }
}
