//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBank.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int user_Code { get; set; }
        public string user_Name { get; set; }
        public string user_Username { get; set; }
        public string user_Password { get; set; }
    }
}
